---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 19.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      enabled: true
      adminPassword: prom-operator
      ingress:
        enabled: true
        hosts:
          - grafana.192.168.64.8.nip.io
        annotations:
          kubernetes.io/ingress.class: nginx
  interval: 1m0s
  releaseName: prometheus-operator
  targetNamespace: monitoring
